#!/bin/bash -f

path=$1
payload=$2
shopt -s globstar

if [[ -f $path ]]; then
  h=$(head -c 4 $path)
  h=${h:1:3}
  if [[ $h = ELF ]];then
    echo $path
      ./build/detector $path $payload
    echo
    echo
  fi

elif [[ -d $path ]];then
  for file in `ls -d $path/**`
    do
      if [[ -f $file ]]; then
        h=$(head -c 4 $file)
        h=${h:1:3}
        if [[ $h = ELF ]];then
          echo $file
            ./build/detector $file $payload
          echo
          echo
        fi
      fi
    done
fi

